---
# tasks file for httpd
- name: httpd installation
  ansible.builtin.yum:
    name: httpd
    state: present
    update_cache: yes
- name: copy file with owner name and permission
  ansible.builtin.copy:
    src: /root/playbooks/httpd/files/index.html
    dest: /var/www/html/
    owner: root
    group: root
    mode: "0644"
